    -- Creates daily_delivery_report if it doesn't exists
    
    create table if not exists {{ params.database }}.{{ params.schema }}.daily_delivery_report 
    (
        report_date date,
        delivery_id varchar,
        order_number int,
        shipment_date date,
        expected_delivery_date date,
        actual_delivery_date date,
        customer_name varchar,
        customer_address varchar,
        customer_city varchar,
        customer_country varchar,
        postal_code varchar,
        product_name varchar,
        product_category varchar,
        product_subcategory varchar,
        quantity integer,
        weight_kg float,
        volume_cubic_meters float,
        vehicle_type varchar,
        vehicle_license_plate varchar,
        driver_name varchar,
        driver_license varchar,
        carrier_name varchar,
        origin_warehouse_name varchar,
        destination_city varchar,
        route_code varchar,
        status varchar,
        delivery_time_hours float,
        distance_km float,
        fuel_used_liters float,
        delivery_cost_usd float,
        insurance_cost_usd float,
        late_delivery_penalty_usd float,
        traffic_condition varchar,
        weather_condition varchar,
        driver_notes varchar,
        customer_feedback varchar
    );